# Shell variables
# Generated by 'wal'
wallpaper='/home/dominee/Pictures/wallpapers/Techno-Geek.png'

# Special
background='#05050F'
foreground='#d7d4ea'
cursor='#d7d4ea'

# Colors
color0='#05050F'
color1='#38468D'
color2='#384BAC'
color3='#3454AC'
color4='#5055A0'
color5='#BF63BA'
color6='#50BEEA'
color7='#d7d4ea'
color8='#9694a3'
color9='#38468D'
color10='#384BAC'
color11='#3454AC'
color12='#5055A0'
color13='#BF63BA'
color14='#50BEEA'
color15='#d7d4ea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
