## Colors configuration
[colors.primary]
background = "#05050F"
foreground = "#d7d4ea"

[colors.normal]
black   = "#05050F"
red     = "#38468D"
green   = "#384BAC"
yellow  = "#3454AC"
blue    = "#5055A0"
magenta = "#BF63BA"
cyan    = "#50BEEA"
white   = "#d7d4ea"

[colors.bright]
black   = "#9694a3"
red     = "#38468D"
green   = "#384BAC"
yellow  = "#3454AC"
blue    = "#5055A0"
magenta = "#BF63BA"
cyan    = "#50BEEA"
white   = "#d7d4ea"
